# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python application

on:
  push:
    branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

      env:
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        DEV_MONGO_HOST: ${{ secrets.DEV_MONGO_HOST }}
        DEV_MONGO_PORT: ${{ secrets.DEV_MONGO_PORT }}
        DEV_MONGO_URL: ${{ secrets.DEV_MONGO_URL }}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Format
      run: |
        python -m black .
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Unit test 
      run: |
        python -m unittest discover


  publish:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Testing publish step
      run: |
        echo "This is working!"
